language: swift

osx_image: xcode1.11.4
env:
  matrix:
    - TEST_SDK=iphonesimulator13.4.1 OS=13.4.1 NAME='iPhone 11 Pro'

script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -project SwiftyS4Lib.xcodeproj -scheme SwiftyS4Lib -sdk $TEST_SDK -destination "platform=iOS Simulator,OS=$OS,name=$NAME" ONLY_ACTIVE_ARCH=YES
